---
- name: Install dependencies
  apt :
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - python-pyaudio
    - python3-pyaudio
    - sox
    - python-pip
    - python3-pip
    - libatlas-base-dev
  become: true

- name: Install pyaudio
  pip: 
    name: pyaudio
  become: true

- name: Set up audio
  copy:
    dest: "~/.asoundrc"
    src: "asoundrc"

- name: Download snowboy
  get_url:
    url: "https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/{{ snowboy_version }}.tar.bz2"
    dest: /tmp/snowboy.tar.bz2

- file:
    path: /opt/shell
    state: directory
    owner: pi
    group: pi
  become: true

- name: Unarchive snowboy
  unarchive:
    src: /tmp/snowboy.tar.bz2
    dest: /opt/shell
    owner: pi
    group: pi
    remote_src: yes

- name: rename snowboy folder
  command: "mv /opt/shell/{{ snowboy_version }} /opt/shell/snowboy"

- name: remove snowboy.tar.bz2
  file:
    state: absent
    path: "/tmp/snowboy.tar.bz2"