- name: copy hotword for snowboy
  copy:
    dest: "/opt/shell/snowboy/resources/"
    src: "Hey Shell.pmdl"

- name: add __init__.py for import
  file:
    path: /opt/shell/snowboy/__init__.py
    state: touch

- name: copy main script file
  copy:
    dest: "/opt/shell"
    src: "main.py"

- name: Install wave
  pip: 
    name: wave
  become: true

- name: Create log folder
  file:
    path: /var/log/shell
    state: directory
    owner: pi
    group: pi
  become: true